[package]
name = "vertigo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "vertc"
path = "src/compiler/main.rs"

[[bin]]
name = "vertigo"
path = "src/virtual-machine/main.rs"

[dependencies]
